name: Make Windows Release From Pushed Version Tag
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    name: Windows Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: ./build.sh
        shell: bash
      - run: cp /c/mingw64/bin/libgcc_s_seh-1.dll output/
        shell: bash
      - run: cp /c/mingw64/bin/libstdc++-6.dll output/
        shell: bash
      - run: cp /c/mingw64/bin/libwinpthread-1.dll output/
        shell: bash
      - run: cp LICENSE.txt output/
        shell: bash
      - run: cp README.md output/
        shell: bash
      - uses: thedoctor0/zip-release@master
        with:
          type: zip
          directory: output
          filename: ../heic2png.zip
      - uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: true
          files: heic2png.zip
          generate_release_notes: true
