name: Run Tests
on: [pull_request]
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-mingw@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.7
      - run: go test ./...
        shell: bash
      - run: ./build.sh
        shell: bash
